repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.76.0
  hooks:
     - id: terraform_fmt
       args:
        - --args=-diff
        - --args=-write=true
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.76.0
  hooks:
    - id: terraform_docs
      args: 
        - --args=--hide=requirements
        - --args=--hide=providers
        - --args=--output-mode=inject
        - --hook-config=--path-to-file=INFO.md
        - --hook-config=--add-to-existing-file=true    
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.4.0
  hooks:
     - id: detect-secrets
       args: ['--baseline', '.secrets.baseline']
       exclude: package.lock.json
